# Publishes a release to crates.io
name: PublishRelease

on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

jobs:
  # publish the current repo state to crates.io
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
